# Default values for quibbble-corner

replicaCount: 1

allowOrigins: []

port: 8080

ingress:
  host: ""
  port: 80

image:
  repository: docker.io/quibbble/lobbies
  tag: latest
  pullPolicy: IfNotPresent
