apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quibbble-lobbies.fullname" . }}
  labels:
    {{- include "quibbble-lobbies.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quibbble-lobbies.selectorLabels" . | nindent 6 }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "quibbble-lobbies.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: quibbble-lobbies
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: quibbble-controller
              key: auth-key
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 3
